# Generated by Django 3.2.1 on 2021-11-19 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=50)),
                ('opens_at', models.TimeField(default=datetime.time(12, 0))),
                ('closes_at', models.TimeField(default=datetime.time(23, 59, 59))),
                ('address', models.CharField(default='No address', max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('delivery_cost', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carpet_cleaning', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
