# Generated by Django 3.2.10 on 2022-01-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpetShops', '0002_alter_carpetcleaning_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpetcleaning',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
    ]
