# Generated by Django 3.2.10 on 2022-01-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarpetShops', '0003_carpetcleaning_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpetcleaning',
            name='number_of_voters',
            field=models.IntegerField(default=0),
        ),
    ]
