# Generated by Django 3.2 on 2022-01-06 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarpetShops', '0004_carpetcleaning_number_of_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=256, null=True)),
                ('carpet_cleaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarpetShops.carpetcleaning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
